// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	PlanetGroups      string
	PlanetUsers       string
	PlantGroupMembers string
}{
	PlanetGroups:      "planet_groups",
	PlanetUsers:       "planet_users",
	PlantGroupMembers: "plant_group_members",
}
